### ISSUE TITLE
add new Control

### ISSUE THREAD

**Issue by Lusifug** [raspberrypi/libcamera#88]
Is there a way to add new values to ControlInfoMap for Camera?
I have added new controls to control_ids and ipa_base, but when I try to use them, I receive an error message:
_ERROR Controls controls.cpp:1069 Control 0x0000000c is not valid for /base/soc/i2c0mux/i2c@1/imx708@1a_
According to the validation method, it seems like this happens cause Camera ControlInfoMap doesn`t have such controls

**Comment by naushir** [comment]
Can you expand on what you are trying to do here?  The control error above is for a V4L2 control error, not a libcamera control.

**Comment by Lusifug** [comment]
I`m trying to add a possibility to pass value via controls, to change params for existing contrast algorithm on the fly, such as low level, low histogram...

**Comment by naushir** [comment]
Unfortunately I am still not sure what you are trying to do. Would you be able to share snippets of source code showing you setting up this new control and how use use it please?

**Comment by Lusifug** [comment]
I`ve added setters to [Contrast](https://github.com/raspberrypi/libcamera/blob/main/src/ipa/rpi/controller/rpi/contrast.h) class:
```
	void setConfigLoHistogram(double loHistogram) override;
	void setConfigLoLevel(double loLevel) override;
	void setConfigLoMax(double loMax) override;
	void setConfigHiHistogram(double hiHistogram) override;
	void setConfigHiLevel(double hiLevel) override;
	void setConfigHiMax(double hiMax) override;
```
and interface to [ContrastAlgorithm](https://github.com/raspberrypi/libcamera/blob/release-v0.0.5%2B83-bde9b04f/src/ipa/rpi/controller/contrast_algorithm.h) class:
```
	virtual void setConfigLoHistogram(double loHistogram) = 0;
	virtual void setConfigLoLevel(double loLevel) = 0;
	virtual void setConfigLoMax(double loMax) = 0;
	virtual void setConfigHiHistogram(double hiHistogram) = 0;
	virtual void setConfigHiLevel(double hiLevel) = 0;
	virtual void setConfigHiMax(double hiMax) = 0;
```

in [IpaBase](https://github.com/raspberrypi/libcamera/blob/main/src/ipa/rpi/common/ipa_base.cpp) method applyControls I`ve added cases for this new controls:
```
case controls::CONTRAST_LO_HISTOGRAM: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_LO_HISTOGRAM - no contrast algorithm";
				break;
			}

			contrast->setConfigLoHistogram(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastLoHistogram,
					       ctrl.second.get<float>());
			break;
		}

		case controls::CONTRAST_LO_LEVEL: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_LO_LEVEL - no contrast algorithm";
				break;
			}

			contrast->setConfigLoLevel(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastLoLevel,
					       ctrl.second.get<float>());
			break;
		}

		case controls::CONTRAST_LO_MAX: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_LO_MAX - no contrast algorithm";
				break;
			}

			contrast->setConfigLoMax(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastLoMax,
					       ctrl.second.get<float>());
			break;
		}

		case controls::CONTRAST_HI_HISTOGRAM: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_HI_HISTOGRAM - no contrast algorithm";
				break;
			}

			contrast->setConfigHiHistogram(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastHiHistogram,
					       ctrl.second.get<float>());
			break;
		}

		case controls::CONTRAST_HI_LEVEL: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_HI_LEVEL - no contrast algorithm";
				break;
			}

			contrast->setConfigHiLevel(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastHiLevel,
					       ctrl.second.get<float>());
			break;
		}

		case controls::CONTRAST_HI_MAX: {
			RPiController::ContrastAlgorithm *contrast = dynamic_cast<RPiController::ContrastAlgorithm *>(
				controller_.getAlgorithm("contrast"));
			if (!contrast) {
				LOG(IPARPI, Warning)
					<< "Could not set CONTRAST_HI_MAX - no contrast algorithm";
				break;
			}

			contrast->setConfigHiMax(ctrl.second.get<float>());
			libcameraMetadata_.set(controls::ContrastHiMax,
					       ctrl.second.get<float>());
			break;
		}
```

and in [control_ids.yaml](https://github.com/raspberrypi/libcamera/blob/main/src/libcamera/control_ids.yaml) I`ve added new values for new controls:
```
  - ContrastLoHistogram:
      type: float
      description:  |
        Specify a low end higher quantile value.

  - ContrastLoLevel:
      type: float
      description:  |
        Specify a lower level in the output range.

  - ContrastLoMax:
      type: float
      description:  |
        Specify a low end desired adjustment value.

  - ContrastHiHistogram:
      type: float
      description:  |
        Specify a high end higher quantile value.

  - ContrastHiLevel:
      type: float
      description:  |
        Specify a high end desired adjustment value.

  - ContrastHiMax:
      type: float
      description:  |
        Specify a high end desired adjustment value.
```
